use colored::Colorize;
use std::fs;
use std::path::Path;

use crate::config::KarbonConfig;

pub fn run(config: &KarbonConfig, root: &Path, target: &str) -> Result<(), String> {
    println!(
        "\n{}  deploy {}\n",
        "▲ karbon".bold().red(),
        target.bold().cyan()
    );

    match target {
        "docker" | "dockerfile" => generate_dockerfile(config, root),
        "ssh" => deploy_ssh(config, root),
        _ => Err(format!(
            "Unknown deploy target '{}'. Available: docker, ssh",
            target
        )),
    }
}

fn validate_shell_safe(s: &str, field: &str) -> Result<(), String> {
    if s.contains(';') || s.contains('&') || s.contains('|') || s.contains('`')
        || s.contains('$') || s.contains('\n') || s.contains("..") {
        return Err(format!("{field} contains unsafe characters: {s}"));
    }
    Ok(())
}

fn generate_dockerfile(config: &KarbonConfig, root: &Path) -> Result<(), String> {
    let package = &config.backend.package;
    let frontend_dir = &config.frontend.dir;
    let serve_cmd = &config.frontend.serve_cmd;
    let port = config.backend.port;

    // Validate all config values that will be embedded in shell/Dockerfile
    validate_shell_safe(package, "backend.package")?;
    validate_shell_safe(frontend_dir, "frontend.dir")?;
    validate_shell_safe(serve_cmd, "frontend.serve_cmd")?;

    let dockerfile = format!(
        r#"# ──────────────────────────────────────────────
# Karbon — Multi-stage production Dockerfile
# Generated by `karbon deploy docker`
# ──────────────────────────────────────────────

# Stage 1: Build frontend
FROM node:20-alpine AS frontend-builder
WORKDIR /app/{frontend_dir}
COPY {frontend_dir}/package*.json ./
RUN npm ci
COPY {frontend_dir}/ ./
RUN npm run build

# Stage 2: Build backend
FROM rust:1.85-slim AS backend-builder
WORKDIR /app
RUN apt-get update && apt-get install -y pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*
COPY Cargo.toml Cargo.lock ./
COPY app/ app/
RUN cargo build --release -p {package}

# Stage 3: Runtime
FROM debian:bookworm-slim AS runtime
RUN apt-get update && apt-get install -y ca-certificates curl nodejs npm && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy backend binary
COPY --from=backend-builder /app/target/release/{package} /app/{package}

# Copy frontend build
COPY --from=frontend-builder /app/{frontend_dir}/build /app/{frontend_dir}/build
COPY --from=frontend-builder /app/{frontend_dir}/package*.json /app/{frontend_dir}/

# Install production node dependencies for SSR
WORKDIR /app/{frontend_dir}
RUN npm ci --omit=dev
WORKDIR /app

# Copy migrations and .env template
COPY migration/ /app/migration/
COPY .env.example /app/.env.example

# Startup script
RUN echo '#!/bin/sh' > /app/start.sh && \
    echo 'cd /app/{frontend_dir} && PORT=3004 {serve_cmd} &' >> /app/start.sh && \
    echo 'FRONTEND_PID=$!' >> /app/start.sh && \
    echo 'sleep 1' >> /app/start.sh && \
    echo 'KARBON_FRONTEND_URL=http://127.0.0.1:3004 /app/{package}' >> /app/start.sh && \
    echo 'kill $FRONTEND_PID 2>/dev/null' >> /app/start.sh && \
    chmod +x /app/start.sh

ENV RUST_LOG=info
EXPOSE {port}

CMD ["/app/start.sh"]
"#
    );

    let path = root.join("Dockerfile");
    fs::write(&path, dockerfile)
        .map_err(|e| format!("Cannot write Dockerfile: {e}"))?;

    println!("  {} Dockerfile generated", "✓".green());

    // Generate .dockerignore too
    let dockerignore = r#"target/
node_modules/
.git/
.env
*.log
"#;

    let ignore_path = root.join(".dockerignore");
    if !ignore_path.exists() {
        fs::write(&ignore_path, dockerignore)
            .map_err(|e| format!("Cannot write .dockerignore: {e}"))?;
        println!("  {} .dockerignore generated", "✓".green());
    }

    println!("\n  {}  Build and run with:", "→".blue());
    println!("     docker build -t {} .", config.app.name);
    println!("     docker run -p {port}:{port} --env-file .env {}\n", config.app.name);

    Ok(())
}

fn deploy_ssh(config: &KarbonConfig, root: &Path) -> Result<(), String> {
    // Read deploy config from karbon.toml [deploy] section or env vars
    let host = std::env::var("DEPLOY_HOST")
        .map_err(|_| "DEPLOY_HOST env var not set. Set it to user@host".to_string())?;
    let deploy_dir = std::env::var("DEPLOY_DIR")
        .unwrap_or_else(|_| format!("/opt/{}", config.app.name));
    let service_name = std::env::var("DEPLOY_SERVICE")
        .unwrap_or_else(|_| config.app.name.clone());

    let package = &config.backend.package;

    // Step 1: Build
    println!("  {} Building for production...", "→".blue());
    crate::commands::build::run(config, root)?;

    // Step 2: Upload binary
    let binary_path = root.join(format!("target/release/{package}"));
    if !binary_path.exists() {
        return Err(format!("Binary not found at {}", binary_path.display()));
    }

    println!("  {} Uploading binary to {}:{}...", "→".blue(), host, deploy_dir);

    let scp = std::process::Command::new("scp")
        .args([
            binary_path.to_str().unwrap(),
            &format!("{host}:{deploy_dir}/{package}"),
        ])
        .status()
        .map_err(|e| format!("Failed to run scp: {e}"))?;

    if !scp.success() {
        return Err("scp failed".to_string());
    }

    // Step 3: Upload frontend build
    let frontend_build = config.frontend_dir(root).join("build");
    if frontend_build.exists() {
        println!("  {} Uploading frontend build...", "→".blue());
        let rsync = std::process::Command::new("rsync")
            .args([
                "-avz", "--delete",
                frontend_build.to_str().unwrap(),
                &format!("{host}:{deploy_dir}/{}/", config.frontend.dir),
            ])
            .status()
            .map_err(|e| format!("Failed to run rsync: {e}"))?;

        if !rsync.success() {
            return Err("rsync failed".to_string());
        }
    }

    // Step 4: Upload migrations
    let migration_dir = root.join("migration");
    if migration_dir.exists() {
        println!("  {} Uploading migrations...", "→".blue());
        let rsync = std::process::Command::new("rsync")
            .args([
                "-avz",
                migration_dir.to_str().unwrap(),
                &format!("{host}:{deploy_dir}/"),
            ])
            .status()
            .map_err(|e| format!("Failed to run rsync: {e}"))?;

        if !rsync.success() {
            return Err("rsync failed".to_string());
        }
    }

    // Step 5: Restart service
    println!("  {} Restarting service {}...", "→".blue(), service_name);
    let restart = std::process::Command::new("ssh")
        .args([
            &host,
            &format!("sudo systemctl restart {service_name}"),
        ])
        .status()
        .map_err(|e| format!("Failed to restart service: {e}"))?;

    if !restart.success() {
        return Err(format!("Failed to restart {service_name}"));
    }

    println!(
        "\n  {} Deployed to {}\n",
        "✓".green().bold(),
        host.bold()
    );

    Ok(())
}
